### PR TITLE
Minor changes that were spotted during Twitch stream

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@AdmiringWorm let me know if anything needs to be fixed up.

**Comment by AdmiringWorm** [comment]
Just a small change on the commit messages is needed.
The scope should be the name of the generator (in this case `build`), and not `template`, if you would be able to change that, then that would be great :)

**Comment by AdmiringWorm** [comment]
@gep13 your changes have been merged, thank you for your contribution

@all-contributors please add @gep13 for code, bug

**Comment by gep13** [comment]
@AdmiringWorm apologies, I jumped onto a call, and didn't see these notifications.

Thanks for merging!

**Comment by AdmiringWorm** [comment]
@gep13 no worries, while I needed to rebase the changes anyhow, so it was not a problem anyway.

**Pull request merged**
